#!/usr/bin/env python3
# Generates source/font_awesome.jai from Font Awesome icons.json metadata.
#
# Jai does not have a JSON parser module available in the compiler/metaprogram
# context, so icon generation uses Python rather than a Jai metaprogram function.
#
# Usage:
#   python3 modules/font_awesome/generate.py <icons.json> <output.jai>
#
# See modules/font_awesome/README.md for upgrade instructions.

import json, sys

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <icons.json> <output.jai>", file=sys.stderr)
        sys.exit(1)

    icons_json_path = sys.argv[1]
    output_path     = sys.argv[2]

    with open(icons_json_path, encoding="utf-8") as f:
        icons = json.load(f)

    # Collect free solid and/or regular icons whose codepoints are in the
    # Private Use Area (U+E000-U+F8FF).  FA also defines glyphs for ASCII
    # digit/letter codepoints (U+0030-U+0039 etc.); excluding those prevents
    # them from overriding the main text font's digits and letters when the FA
    # font is merged into the ImGui atlas.
    entries = []
    seen_codepoints = set()
    for name, info in icons.items():
        free_styles = info.get("free", [])
        has_solid   = "solid"   in free_styles
        has_regular = "regular" in free_styles
        if not (has_solid or has_regular):
            continue
        unicode_hex = info.get("unicode", "")
        if not unicode_hex:
            continue
        cp = int(unicode_hex, 16)
        if cp < 0xE000:
            continue
        if cp in seen_codepoints:
            continue
        seen_codepoints.add(cp)
        styles = []
        if has_solid:   styles.append("S")
        if has_regular: styles.append("R")
        const_name = "ICON_FA_" + name.upper().replace("-", "_")
        entries.append((cp, const_name, unicode_hex.upper(), styles))

    entries.sort()

    lines = [
        "// FontAwesome 7 Free - Solid (S) and Regular/outline (R) icon codepoints.",
        "// DO NOT EDIT: auto-generated by modules/font_awesome/generate.py",
        "//",
        "// Jai does not have a JSON parser module available in the compiler/metaprogram",
        "// context, so icon generation uses Python rather than a Jai metaprogram function.",
        "//",
        "// Apache 2.0 license (fonts and icons): https://fontawesome.com/license/free",
        "",
        "// Glyph range for the ImGui font atlas.  Must persist for the atlas lifetime.",
        "// Pass as the glyph_ranges argument to AddFontFromMemoryTTF when merging the",
        "// Solid or Regular FA font.",
        "FONT_AWESOME_GLYPH_RANGES : [3]ImGui.ImWchar : .[0xe000, 0xf8ff, 0];",
        "",
        "// One constant per icon.  Solid and Regular use the same codepoint; push",
        "// app.font_set.fa_solid or app.font_set.fa_regular to choose the visual style.",
    ]

    for cp, cname, uhex, styles in entries:
        style_str = "+".join(styles)
        lines.append(f'{cname} :: "\\u{uhex}"; // {style_str}')

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[font_awesome] Generated {len(entries)} icon constants -> {output_path}")

if __name__ == "__main__":
    main()
